Q1). Write a lambda function that takes an integer 'year' and returns 'age'.

In [2]:
from datetime import datetime

current_year = datetime.now().year

Q2) Write a lambda function that takes a float "cost" and returns a float "price" by adding 10% to the cost.

In [3]:
add_10_percent = lambda cost: cost + (cost*0.1)

add_10_percent(10)

11.0

Q3) Write a lambda function that takes two strings 'name' , 'domain' and returns an email address (string).

In [5]:
make_email = lambda name, domain: name + "@" + domain 

make_email("aungkhantbwar.alexander", "gmail.com")

'aungkhantbwar.alexander@gmail.com'

Q4) Lambda in Data Science/Data Analysis

In [40]:
import pandas as pd

df = pd.read_csv("../data/rentals.csv")

# Q4.1) Create a new column called "size" where each entry is 
# determined by the number of bathrooms: 'large' if the number of bathrooms is greater than 3, and 'small' otherwise.


df["size"] = df["bathrooms"].apply(lambda x: "large" if x > 3 else "small")



# -----------------------------------------------------------------#
# Q4.2) Creat a new column called "price_category" where 
# Assign each entry as the following categories based on the price:
# If the price is greater than 100, the category should be 'premium'.
# Otherwise, the category should be 'standard'.

df["price_category"] = df["price"].apply(lambda x: "premium" if float(x.split("$")[1].replace(",", "")) > 100.0 else "standard")



# -----------------------------------------------------------------#
# Do not change the code below: 
# Print the first five rows to see the data. You should have 11 columns

print(f"DataFrame has {df.shape[1]} columns")
df.head()

DataFrame has 11 columns

,id,latitude,longitude,property_type,room_type,bathrooms,bedrooms,minimum_nights,price,size,price_category
0,958,37.76931,-122.43386,Apartment,Entire home/apt,1.0,1.0,1,$170.00,small,premium
1,3850,37.75402,-122.45805,House,Private room,1.0,1.0,1,$99.00,small,standard
2,5858,37.74511,-122.42102,Apartment,Entire home/apt,1.0,2.0,30,$235.00,small,premium
3,7918,37.76669,-122.45250,Apartment,Private room,4.0,1.0,32,$65.00,large,standard
4,8142,37.76487,-122.45183,Apartment,Private room,4.0,1.0,32,$65.00,large,standard

In [37]:
df.head()

,id,latitude,longitude,property_type,room_type,bathrooms,bedrooms,minimum_nights,price,size
0,958,37.76931,-122.43386,Apartment,Entire home/apt,1.0,1.0,1,$170.00,small
1,3850,37.75402,-122.45805,House,Private room,1.0,1.0,1,$99.00,small
2,5858,37.74511,-122.42102,Apartment,Entire home/apt,1.0,2.0,30,$235.00,small
3,7918,37.76669,-122.45250,Apartment,Private room,4.0,1.0,32,$65.00,large
4,8142,37.76487,-122.45183,Apartment,Private room,4.0,1.0,32,$65.00,large

In [ ]:
price = "$200"

price.split("$")[1]

In [41]:
!ls ../data

Course Evaluation_Parami.csv Q2_output.txt
HR_5000 Records.csv          ball.bmp
Q1.txt                       rentals.csv
Q1_output.txt                students.csv
Q2.txt                       students_clean.csv
Q2_names_processed.txt

# List Comprehension exercises

In [47]:
l = [3, 4, 4, 1, 0, 9, 3, 5, 7, 8]

diff_l = [l[idx] - l[idx+1] for idx in range(len(l)-1)]
diff_l

[-1, 0, 3, 1, -9, 6, -2, -2, -1]

In [50]:
password_list = ["asdfl39", "i8383jwer", "9u2jhowdjfa8dsf", "329osdof"]

valid_passwords = [password for password in password_list if len(password) >= 8]
valid_passwords

['i8383jwer', '9u2jhowdjfa8dsf', '329osdof']

In [52]:
ll = [34, 45, 3343, 3533, 222, 48934]

greater_than_100 = [num for num in ll if num > 100]
greater_than_100

[3343, 3533, 222, 48934]

In [ ]:
for num in range(1, 1000):
    if len(str(num)) == 1:
        print(num)
    elif len(str(num)) == 2:
        if str(num)[0] == str(num)[1]:
            print(num)
    elif len(str(num)) == 3:
        if str(num)[0] == str(num)[2]:
            print(num)

In [63]:
palindromic_nums = [num for num in range(1, 1000) if str(num) == str(num)[::-1]]

palindromic_nums

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 11,
 22,
 33,
 44,
 55,
 66,
 77,
 88,
 99,
 101,
 111,
 121,
 131,
 141,
 151,
 161,
 171,
 181,
 191,
 202,
 212,
 222,
 232,
 242,
 252,
 262,
 272,
 282,
 292,
 303,
 313,
 323,
 333,
 343,
 353,
 363,
 373,
 383,
 393,
 404,
 414,
 424,
 434,
 444,
 454,
 464,
 474,
 484,
 494,
 505,
 515,
 525,
 535,
 545,
 555,
 565,
 575,
 585,
 595,
 606,
 616,
 626,
 636,
 646,
 656,
 666,
 676,
 686,
 696,
 707,
 717,
 727,
 737,
 747,
 757,
 767,
 777,
 787,
 797,
 808,
 818,
 828,
 838,
 848,
 858,
 868,
 878,
 888,
 898,
 909,
 919,
 929,
 939,
 949,
 959,
 969,
 979,
 989,
 999]